(function(g){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var F4=function(a){a.X("cardstatechange",a.xi()&&a.cm()?1:0)},G4=function(a,b){var c=g.Oa(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},B0a=function(a){var b=g.Gl(a);
a=g.Jl(a);return new g.vl(b.x,b.y,a.width,a.height)},C0a=function(a){return Math.pow(a,3)},D0a=function(a){return 3*a*a-2*a*a*a},J4=function(a){a=g.Ra(a);
delete H4[a];g.Af(H4)&&I4&&I4.stop()},F0a=function(){I4||(I4=new g.Wn(function(){E0a()},20));
var a=I4;a.isActive()||a.start()},E0a=function(){var a=g.Ua();
g.nf(H4,function(b){G0a(b,a)});
g.Af(H4)||F0a()},K4=function(a,b,c,d){g.po.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.u=a;this.N=b;this.duration=c;this.I=d;this.coords=[];this.progress=this.J=0;this.D=null},G0a=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.J=1E3/(b-a.D);a.D=b;H0a(a,a.progress);1==a.progress?(a.j=0,J4(a),a.onFinish(),a.Iz()):a.Nc()&&a.hF()},H0a=function(a,b){"function"===typeof a.I&&(b=a.I(b));
a.coords=Array(a.u.length);for(var c=0;c<a.u.length;c++)a.coords[c]=(a.N[c]-a.u[c])*b+a.u[c]},I0a=function(a,b){g.ff.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.J;this.state=b.j},L4=function(a,b,c,d,e){K4.call(this,b,c,d,e);
this.element=a},J0a=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
L4.call(this,a,b,c,d,e)},M4=function(a){g.L.call(this);
this.u=a||window;this.j=[]},N4=function(a){return a.baseUrl||null},O4=function(a,b){return g.xm(g.Qk(a,b),function(c){return!!c})},K0a=function(a,b,c){function d(ca){var O=ca.hovercardButton;
if(!O)return null;O=O.subscribeButtonRenderer;if(!O)return null;var la=f(O.unsubscribedButtonText),oa=f(O.subscribedButtonText);if(O.subscribed){var ya=f(O.subscriberCountWithUnsubscribeText);var va=f(O.subscriberCountText)}else ya=f(O.subscriberCountText),va=f(O.subscriberCountWithSubscribeText);var Aa=null;if(ca.signinEndpoint){Aa=G4(ca,"signinEndpoint","webNavigationEndpointData","url");if(!Aa){var Ka,Ba,ra;Aa=null==(Ka=O.signInEndpoint)?void 0:null==(Ba=Ka.commandMetadata)?void 0:null==(ra=Ba.webCommandMetadata)?
void 0:ra.url}if(!Aa)return null}return la&&(oa||Aa)?{subscribed:O.subscribed,subscribeText:la,subscribeCount:ya,unsubscribeText:oa,unsubscribeCount:va,enabled:O.enabled,signinUrl:Aa,classic:ca.useClassicSubscribeButton}:null}
function e(ca){if(ca){var O=[],la=ca.videoId;la&&O.push("v="+la);(la=ca.playlistId)&&O.push("list="+la);(ca=ca.startTimeSeconds)&&O.push("t="+ca);return"/watch?"+O.join("&")}}
function f(ca){if(!ca)return null;var O=ca.simpleText;return O?O:ca.runs?g.Qk(ca.runs,function(la){return la.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=!1,q=null,v=null,w=null,y=null,A=!1,B=null,E=null,H=null,G=null,I=null,P=null;if("VIDEO"===h)l.urlEndpoint?m=l.urlEndpoint.url:(P=l.watchEndpoint,m=e(P)),n=!1,q=a,b.thumbnailOverlays?(p=b.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,v=f(p.text),p="LIVE"===p.style):v=f(b.videoDuration);else if("PLAYLIST"===h)l.urlEndpoint?m=l.urlEndpoint.url:(P=l.watchEndpoint,m=e(P)),n=!1,q=a,w=f(b.playlistLength);
else if("CHANNEL"===h){if(A=G4(l,"browseEndpoint","browseId"))y=A,m="/channel/"+y;n=!1;q="new";(A=!!b.isSubscribe)?B=d(b):E=f(b.subscribersText)}else"WEBSITE"===h?((H=G4(l,"urlEndpoint","url"))&&(m=H),n=!0,q="new",H=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===h&&(b.productPrice&&(G=f(b.productPrice)),b.additionalFeesText&&(I=f(b.additionalFeesText)),(n=G4(l,"urlEndpoint","url"))&&(m=n),n=!0,q="new");a=G4(b,"title","accessibility","accessibilityData","label");var K=b.endpoint?b.endpoint.clickTrackingParams:
null,Q="";if(b.metadata){var S=f(b.metadata);S&&(Q=S)}return{id:"element-"+c,type:h,title:f(b.title),metadata:Q,callToAction:f(b.callToAction),nO:b.image,iconUrl:H,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:v,isLiveVideo:p,playlistLength:w,channelId:y,subscribeButton:B,subscribersText:E,isSubscribe:A,targetUrl:m||null,wZ:n,sessionData:K?{itct:K}:null,N4:q,Lx:a?a:
null,isPlaceholder:b.isPlaceholder,impressionUrls:O4(b.impressionUrls||[],N4),hZ:O4(b.hovercardShowUrls||[],N4),clickUrls:O4(l.loggingUrls||[],N4),visualElement:g.nz(b.trackingParams),productPrice:G,additionalFeesText:I,watchEndpoint:P||null}},L0a=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:O4(a.impressionUrls||[],N4),elements:O4(a.elements||[],function(d,e){return K0a(b,d,e)})};
a.trackingParams&&(c.visualElement=g.nz(a.trackingParams));return c},M0a=function(a){g.GN.call(this,a);
this.B=this.endscreen=null;this.j={};this.D={};this.C=this.u=null;this.J=[];this.V=!0;this.I=0;a=a.R();this.N=g.LF(a)||g.PF(a);this.W=a.experiments.gb("web_rounded_thumbnails");this.events=new g.SD(this);g.M(this,this.events);this.events.P(this.player,g.nA("creatorendscreen"),this.onCueRangeEnter);this.events.P(this.player,g.oA("creatorendscreen"),this.onCueRangeExit);this.events.P(this.player,"resize",this.yb);this.events.P(window,"focus",this.O2);this.load();var b=g.nh("STYLE");(g.ch("HEAD")[0]||
document.body).appendChild(b);g.ef(this,function(){g.rh(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},N0a=function(a){return a.player.getVideoData().C?"current":a.N?"new":"current"},P4=function(a){return"creator-endscreen-editor"===a.player.R().playerStyle},O0a=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.B&&a.B.abort();c={method:"POST",onFinish:function(e){var f=a.B=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=L0a(f,N0a(a))));Q4(a,f)},
urlParams:{v:c},withCredentials:!0};a.N&&(c.urlParams.ptype="embedded");var d=b.Ds;d&&(c.postParams={ad_tracking:d});if(b=g.NBa(b))if(b=g.rg(b),b=g.kg(b))a.B=g.xu(b,c)},Q4=function(a,b,c){c=void 0===c?!0:c;
a.player.zf("creatorendscreen");a.u&&(a.u.dispose(),a.u=null,a.C.dispose(),a.C=null);for(var d=g.r(Object.values(a.j)),e=d.next();!e.done;e=d.next())e.value.dispose();a.j={};a.D={};0<a.J.length&&(a.J.forEach(function(l){l.dispose()}),a.J.length=0);
a.I=0;if((a.endscreen=b)&&b.elements){c&&P0a(a);c=[];d=new g.lA(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.R().isMobile||(a.u=new g.W({F:"div",L:"ytp-ce-shadow"}),g.qN(a.player,a.u.element,4),a.C=new g.AL(a.u,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=Q0a(a,e);if(f){a.j[e.id]=f;a.D[e.id]=e;g.qN(a.player,f.element,4);var h=new g.lA(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);R0a(a,
f,e)}else g.kz(new g.Kv("buildEndscreenElement null",e))}a.player.ke(c);a.yb()}},P0a=function(a){var b=g.tz(),c=g.uz();
c&&b&&a.endscreen.visualElement&&g.yz(void 0,c,b,[a.endscreen.visualElement])},Q0a=function(a,b){var c=null;
switch(b.type){case "VIDEO":a={F:"div",Da:["ytp-ce-element","ytp-ce-video"],T:{tabindex:"0","aria-label":b.Lx||"","aria-hidden":"true"},S:[{F:"div",L:"ytp-ce-element-shadow"},{F:"div",L:"ytp-ce-covering-image",T:R4(b)},{F:"div",L:"ytp-ce-covering-shadow-top"},{F:"a",L:"ytp-ce-covering-overlay",T:{href:S4(a,b.targetUrl),tabindex:"-1"},S:[{F:"div",Da:["ytp-ce-video-title","ytp-webkit-ellipsis"],T:{dir:g.to(b.title||"")},Z:b.title},{F:"div",L:b.isLiveVideo?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
Z:b.videoDuration||void 0}]}]};c=new g.W(a);break;case "PLAYLIST":a={F:"div",Da:["ytp-ce-element","ytp-ce-playlist"],T:{tabindex:"0","aria-label":b.Lx||"","aria-hidden":"true"},S:[{F:"div",L:"ytp-ce-element-shadow"},{F:"div",L:"ytp-ce-covering-image",T:R4(b)},{F:"div",L:"ytp-ce-covering-shadow-top"},{F:"a",L:"ytp-ce-covering-overlay",T:{href:S4(a,b.targetUrl),tabindex:"-1"},S:[{F:"div",Da:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],T:{dir:g.to(b.title||"")},Z:b.title},{F:"div",L:"ytp-ce-playlist-count",
S:[{F:"div",L:"ytp-ce-playlist-icon"},{F:"div",L:"ytp-ce-playlist-count-text",Z:b.playlistLength||void 0}]}]}]};c=new g.W(a);break;case "CHANNEL":c={F:"div",Da:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],T:{tabindex:"0","aria-label":b.Lx||"","aria-hidden":"true"},S:[{F:"div",L:"ytp-ce-element-shadow"},{F:"div",L:"ytp-ce-expanding-overlay",S:[{F:"div",L:"ytp-ce-expanding-overlay-hider"},{F:"div",L:"ytp-ce-expanding-overlay-background"},{F:"div",L:"ytp-ce-expanding-overlay-content",
S:[{F:"div",L:"ytp-ce-expanding-overlay-body",S:[{F:"div",L:"ytp-ce-expanding-overlay-body-padding",S:[{F:"a",Da:["ytp-ce-channel-title","ytp-ce-link"],T:{href:S4(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.to(b.title||"")},Z:b.title},b.subscribeButton?{F:"div",L:"ytp-ce-subscribe-container",S:[{F:"div",L:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{F:"div",L:"ytp-ce-channel-subscribers-text",Z:b.subscribersText}:"",b.metadata?{F:"div",Da:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],Z:b.metadata}:""]}]}]}]},{F:"div",L:"ytp-ce-expanding-image",T:R4(b)}]};c=new g.W(c);var d=g.dh(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.eo(d,"ytp-ce-subscribe-button");if(a.player.R().isMobile){var e=null;var f=b.sessionData.itct}else e="endscreen",f=null;e=new g.LO(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,
!!b.subscribeButton.classic,b.channelId,!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.J.push(e)}break;case "WEBSITE":a={F:"div",Da:["ytp-ce-element","ytp-ce-website"],T:{tabindex:"0","aria-label":b.Lx||"","aria-hidden":"true"},S:[{F:"div",L:"ytp-ce-element-shadow"},{F:"div",L:"ytp-ce-expanding-overlay",S:[{F:"div",L:"ytp-ce-expanding-overlay-hider"},{F:"div",L:"ytp-ce-expanding-overlay-background"},{F:"div",L:"ytp-ce-expanding-overlay-content",
S:[{F:"div",L:"ytp-ce-expanding-overlay-body",S:[{F:"div",L:"ytp-ce-expanding-overlay-body-padding",S:[{F:"div",L:"ytp-ce-website-title",T:{dir:g.to(b.title||"")},Z:b.title},{F:"div",L:"ytp-ce-website-metadata",Z:b.metadata},{F:"a",Da:["ytp-ce-website-goto","ytp-ce-link"],T:{href:S4(a,b.targetUrl),target:"_blank",tabindex:"-1"},Z:b.callToAction}]}]}]}]},{F:"div",L:"ytp-ce-expanding-image",T:R4(b)},{F:"div",L:"ytp-ce-expanding-icon",T:S0a(b.iconUrl)}]};c=new g.W(a);break;case "CREATOR_MERCHANDISE":c=
"",b.productPrice&&(c={F:"div",L:"ytp-ce-merchandise-price-container",S:[{F:"div",L:"ytp-ce-merchandise-price",Z:b.productPrice}]},b.additionalFeesText&&c.S.push({F:"div",L:"ytp-ce-merchandise-additional-fees",Z:b.additionalFeesText})),a={F:"div",Da:["ytp-ce-element","ytp-ce-merchandise"],T:{tabindex:"0","aria-label":b.Lx||"","aria-hidden":"true"},S:[{F:"div",L:"ytp-ce-element-shadow"},{F:"div",L:"ytp-ce-expanding-overlay",S:[{F:"div",L:"ytp-ce-expanding-overlay-hider"},{F:"div",L:"ytp-ce-expanding-overlay-background"},
{F:"div",L:"ytp-ce-expanding-overlay-content",S:[{F:"div",L:"ytp-ce-expanding-overlay-body",S:[{F:"div",L:"ytp-ce-expanding-overlay-body-padding",S:[{F:"div",L:"ytp-ce-merchandise-title",T:{dir:g.to(b.title||"")},Z:b.title},c,{F:"div",L:"ytp-ce-merchandise-metadata",Z:b.metadata},{F:"a",Da:["ytp-ce-merchandise-goto","ytp-ce-link"],T:{href:S4(a,b.targetUrl),target:"_blank",tabindex:"-1"},Z:b.callToAction}]}]}]}]},{F:"div",L:"ytp-ce-expanding-image",T:R4(b)},{F:"div",L:"ytp-ce-merchandise-invideo-cta-container",
S:[{F:"div",L:"ytp-ce-merchandise-invideo-cta",Z:b.callToAction||void 0}]}]},c=new g.W(a)}b.isPlaceholder&&g.eo(c.element,"ytp-ce-placeholder");return c},R4=function(a){if(a.nO)var b=a.nO.thumbnails;
return S0a(b?b[b.length-1].url:null)},S0a=function(a){return a?{style:"background-image: url("+a+")"}:{}},R0a=function(a,b,c){function d(m){m&&(b.Na("blur",function(){"none"!=m.style.display&&a.V&&m.focus()}),b.P(m,"focus",f),b.P(m,"blur",h))}
function e(m){a.I+=m;0<a.I?(g.eo(b.element,"ytp-ce-force-expand"),T4(a,c.id,!0)):(g.go(b.element,"ytp-ce-force-expand"),g.go(b.element,"ytp-ce-element-hover"),T4(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.Na("mouseenter",function(){T0a(a,b,c)});
b.Na("mouseleave",function(){U0a(a,b,c)});
a.player.R().isMobile||b.Na("click",function(){g.eo(b.element,"ytp-ce-element-hover")});
b.Na("click",function(m){V0a(a,c,m)});
b.Na("keypress",function(m){V0a(a,c,m)});
b.Na("focus",function(){T0a(a,b,c)});
b.Na("blur",function(){U0a(a,b,c)});
b.Na("touchstart",function(){T0a(a,b,c)});
var l=g.fh("ytp-ce-expanding-overlay-hider",b.element);l&&b.P(l,"touchstart",function(m){m=m||window.event;m.cancelBubble=!0;m.stopPropagation&&m.stopPropagation();g.go(b.element,"ytp-ce-element-hover");g.go(b.element,"ytp-ce-force-expand")});
b.Na("keydown",function(m){a.V=9===m.keyCode&&!m.shiftKey});
d(g.fh("ytp-sb-subscribe",b.element));d(g.fh("ytp-sb-unsubscribe",b.element));b.Na("focus",f);b.Na("blur",h)},V0a=function(a,b,c){if(b.targetUrl&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.co(d,"ytp-ce-element");){g.co(d,"subscribe-label")&&W0a(a,b);
if(g.co(d,"ytp-ce-channel-subscribe"))return;d=g.sh(d)}if(!d||g.co(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.j[b.id])U0a(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.N4)W0a(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.rg(S4(a,b.targetUrl)),g.$L(g.kg(c),void 0,b.sessionData);else{var e=g.eG(a.player.R())||a.player.getVideoData().C,f=function(){var h=S4(a,b.targetUrl),l=b.sessionData,m=b.watchEndpoint,n=g.iu(h);e&&n&&(n.v||
n.list)?a.player.El(n.v,l,n.list,!1,void 0,m||void 0):g.ZL(h,l)};
W0a(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},S4=function(a,b){a=a.player.R();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.oG(a)+b}else return"";return b},T0a=function(a,b,c){g.co(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.eo(b.element,"ytp-ce-element-hover"):a.player.R().isMobile?(new g.Wn(function(){g.eo(b.element,"ytp-ce-element-hover")},200)).start():g.eo(b.element,"ytp-ce-element-hover"),U4(a,c.hZ),T4(a,c.id,!0))},U0a=function(a,b,c){g.go(b.element,"ytp-ce-element-hover");
g.go(b.element,"ytp-ce-force-expand");T4(a,c.id,!1)},T4=function(a,b,c){a.u&&(c?a.C.show():a.C.hide());
for(var d=g.r(Object.keys(a.j)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.N(a.j[e].element,"ytp-ce-element-shadow-show",c)},U4=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||0===b.length||P4(a))c&&c();else{b=X0a(a,b);var e=0,f=!1,h=new g.Wn(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.Qw(b[a],d)}},W0a=function(a,b,c){U4(a,b.clickUrls,c);
(a=g.uz())&&b.wZ&&g.Ez(a,b.visualElement)},X0a=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(Y0a(b[d],c));return a},Y0a=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},Z0a=function(a){return"string"===typeof a?a:""},V4=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},$0a=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.j=d},W4=function(a){return a.value?a.value:null},X4=function(a){if(!a)return null;
var b=g.rg(Z0a(a.value));b=g.kg(b);if(!b)return null;var c=V4(a.target,a1a,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new $0a(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},b1a=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},e1a=function(a){if(!a)return null;
var b=V4(a.type,c1a),c=V4(a.trigger,d1a);a=a.url;a=Array.isArray(a)&&a.length?a[0]:a;a=X4(a?a:null);return b?new b1a(b,c,a):null},f1a=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},g1a=function(a,b){return g.Ub(a.action,b)},h1a=function(a,b){this.context=a;
this.j=b},i1a=function(a){return a.customMessage?Y4("div","iv-card-message",a.customMessage):""},Z4=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{F:"div",L:"iv-card-image",T:{style:a},S:c}},j1a=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.r(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(Y4("li","",c.value));return{F:"ul",L:"iv-card-meta-info",S:b}},Y4=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.to(c);return{F:a,T:b,Z:c}},k1a=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.Ux&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.Ux+");");c.dir=g.to(a.customMessage);var d=[{F:"span",Z:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({F:"span",L:"iv-card-link-icon"}));return{F:"div",Da:b,T:c,S:d}},$4=function(a,b,c,d){if(d){b=g.r(b);
for(var e=b.next();!e.done;e=b.next())a.j(e.value,d,c.id,c.sessionData,c.tracking.click,5)}},l1a=function(a,b){this.merchant=a;
this.price=b},m1a=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,"").split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},n1a=function(a,b){return b?b:m1a(a)?"current":"new"},a5=function(a,b){g.L.call(this);
var c=this;this.element=a;this.context=b;this.zb=!1;this.Va=new Map;this.Ya=new Map;this.context.G.addEventListener(g.nA("annotations_module"),function(d){(d=c.Va.get(d))&&d.apply(c)});
this.context.G.addEventListener(g.oA("annotations_module"),function(d){(d=c.Ya.get(d))&&d.apply(c)})},b5=function(a,b,c,d,e,f,h){a.context.j.Na(b,"click",function(l){a.iF(c,d,e,f||[],h||0,l)});
a.context.j.Na(b,"touchstart",function(){a.zb=!1});
a.context.j.Na(b,"touchmove",function(){a.zb=!0})},o1a=function(a){var b;
return(null==(b=g.Vu(a,g.JH))?0:b.url)?g.Vu(a,g.JH).url:(a=g.Vu(a,g.GH))&&a.videoId?(b="/watch?v="+a.videoId,a.playlistId&&(b+="&list="+a.playlistId),a.index&&(b+="&index="+a.index),a.startTimeSeconds&&(b+="&t="+a.startTimeSeconds),b):null},c5=function(a,b,c){return{impression:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
GS:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
vE:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},p1a=function(a,b,c){a5.call(this,b,c);
var d=this;this.G=a;this.eventId=null;this.La=this.Ob=this.B=this.isInitialized=!1;this.qa=null;this.cards=[];this.vb=this.N=this.Ia=this.D=this.Ta=this.j=null;this.W=[];this.Y=this.J=this.mf=this.Fa=null;this.I=0;this.va=new g.Wn(function(){},c.U.df?4E3:3E3);
g.M(this,this.va);this.ib=new g.Wn(function(){});
g.M(this,this.ib);this.ra=new h1a(c,function(e,f,h,l,m,n){b5(d,e,f,h,l,m,n)});
this.V=new g.W({F:"div",L:"iv-drawer",T:{id:"iv-drawer"},S:[{F:"div",L:"iv-drawer-header",T:{"aria-role":"heading"},S:[{F:"span",L:"iv-drawer-header-text"},{F:"button",Da:["iv-drawer-close-button","ytp-button"],T:{"aria-label":"Hide cards",tabindex:"0"}}]},{F:"div",L:"iv-drawer-content"}]});g.M(this,this.V);this.C=this.V.element;this.fb=new g.AL(this.V,330);g.M(this,this.fb);this.Fb=g.fh("iv-drawer-header-text",this.C);this.u=g.fh("iv-drawer-content",this.C);this.addCueRange(0,1E3*c.videoData.lengthSeconds,
"",function(){d.Ob&&d5(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Ob=d.B)&&e5(d)});
this.G.addEventListener("videodatachange",this.Rp.bind(this))},q1a=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){d5(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){e5(a)});
var c=b.headerText;g.uh(a.Fb,c);a.N&&a.N.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.Fa=g.nz(b.trackingParams);a.J=g.nz(b.closeTrackingParams);a.mf=g.nz(b.iconTrackingParams)},r1a=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.I,d=a.G.R().experiments.gb("enable_error_corrections_infocard_web_client");
if(!b.content&&b.teaser.simpleCardTeaserRenderer&&d){var e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"simple",teaserText:g.sA(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:{},sponsored:!1,tracking:{},fm:null,Cj:e.trackingParams?g.nz(e.trackingParams):null,mf:f&&f.trackingParams?g.nz(f.trackingParams):null,imageUrl:"",displayDomain:null,
showLinkIcon:!1,Ux:null,title:"",customMessage:"",url:null,onClickCommand:e.onTapCommand||null};f5(a,b)}else{var h;if(null==(h=b.content)?0:h.simpleCardContentRenderer){if(!b.cueRanges.length)return;f=null==(e=b.content)?void 0:e.simpleCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;var l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"simple",teaserText:g.sA(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),
autoOpen:!!b.autoOpen,sessionData:g5(a,c,b,f),sponsored:!1,tracking:c5(f,e,f.command),fm:f.trackingParams?g.nz(f.trackingParams):null,Cj:e.trackingParams?g.nz(e.trackingParams):null,mf:l&&l.trackingParams?g.nz(l.trackingParams):null,imageUrl:h5(f.image.thumbnails,290).url,displayDomain:f.displayDomain?g.sA(f.displayDomain):null,showLinkIcon:!!f.showLinkIcon,Ux:null,title:f.title?g.sA(f.title):"",customMessage:f.callToAction?g.sA(f.callToAction):"",url:g.Vu(f.command,g.JH).url?X4({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.Vu(f.command,g.JH).url}):null,onClickCommand:null};f5(a,b)}else{var m;if(null==(m=b.content)?0:m.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(f=b.content)?void 0:f.collaboratorInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"collaborator",teaserText:g.sA(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),
autoOpen:!!b.autoOpen,sessionData:g5(a,c,b,e),sponsored:!1,tracking:c5(e,f,e.endpoint),fm:e.trackingParams?g.nz(e.trackingParams):null,Cj:f.trackingParams?g.nz(f.trackingParams):null,mf:l&&l.trackingParams?g.nz(l.trackingParams):null,channelId:g.Vu(e.endpoint,i5).browseId,customMessage:e.customText?g.sA(e.customText):null,profileImageUrl:h5(e.channelAvatar.thumbnails,290).url,title:e.channelName?g.sA(e.channelName):"",metaInfo:[e.subscriberCountText?g.sA(e.subscriberCountText):""],url:X4({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.Vu(e.endpoint,i5).canonicalBaseUrl?g.Vu(e.endpoint,i5).canonicalBaseUrl:"/channel/"+g.Vu(e.endpoint,i5).browseId}),onClickCommand:null};f5(a,b)}else{var n;if(null==(n=b.content)?0:n.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(l=b.content)?void 0:l.playlistInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"playlist",teaserText:g.sA(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:g5(a,c,b,e),sponsored:!1,tracking:c5(e,f,e.action),fm:e.trackingParams?g.nz(e.trackingParams):null,Cj:f.trackingParams?g.nz(f.trackingParams):null,mf:l&&l.trackingParams?g.nz(l.trackingParams):null,xA:h5(e.playlistThumbnail.thumbnails,258).url,customMessage:e.customMessage?g.sA(e.customMessage):null,playlistVideoCount:g.sA(e.playlistVideoCount),title:e.playlistTitle?g.sA(e.playlistTitle):"",metaInfo:[e.channelName?
g.sA(e.channelName):"",e.videoCountText?g.sA(e.videoCountText):""],url:X4({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:o1a(e.action)}),onClickCommand:null};f5(a,b)}else{var p;if(null==(p=b.content)?0:p.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;var q;e=null==(q=b.content)?void 0:q.videoInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"video",teaserText:g.sA(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:g5(a,c,b,e),sponsored:!1,tracking:c5(e,f,e.action),fm:e.trackingParams?g.nz(e.trackingParams):null,Cj:f.trackingParams?g.nz(f.trackingParams):null,mf:l&&l.trackingParams?g.nz(l.trackingParams):null,xA:h5(e.videoThumbnail.thumbnails,258).url,videoDuration:e.lengthString?g.sA(e.lengthString):null,customMessage:e.customMessage?g.sA(e.customMessage):null,title:e.videoTitle?g.sA(e.videoTitle):"",metaInfo:[e.channelName?
g.sA(e.channelName):"",e.viewCountText?g.sA(e.viewCountText):""],isLiveNow:!!e.badge,url:X4({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:o1a(e.action)}),onClickCommand:null};f5(a,b)}}}}}a.I++},h5=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},g5=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},t1a=function(a,b){if(b=s1a(a,b))b===a.j&&(a.j=null),a.G.removeCueRange(b.card.id),g.rh(b.wG),g.Zb(a.cards,b),a.yB(),j5(a)},d5=function(a,b,c){if(!a.B){a.fb.show();
a.Ta=new g.Wn(function(){g.eo(a.context.G.getRootNode(),g.aT.IV_DRAWER_OPEN)},0);
a.Ta.start();a.qa=g.ux(a.u,"mousewheel",function(h){a.va.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.u.scrollTop+=h});
a.B=!0;var d=g.uz();d&&a.Fa&&a.J&&g.Cz(d,[a.Fa,a.J]);b={TRIGGER_TYPE:b};for(var e=g.r(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.bQ||(f.bQ=!0,u1a(a.context.logger,f.card.tracking.impression,b)),d&&g.Cz(d,[f.card.fm]);F4(a.G);c&&(a.D=new g.Wn(function(){a.Ia=a.N;a.vb.focus()},330),a.D.start())}},e5=function(a){a.B&&(a.fb.hide(),g.vx(a.qa),a.qa=null,g.go(a.context.G.getRootNode(),g.aT.IV_DRAWER_OPEN),a.B=!1,F4(a.G),a.D&&a.D.stop(),a.D=new g.Wn(function(){a.Ia&&(a.Ia.focus(),a.Ia=null)},330),
a.D.start())},w1a=function(a){g.fo(a.element,[g.aT.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.qN(a.G,a.C,5);v1a(a);a.N=g.fh("ytp-cards-button",a.G.getRootNode());a.vb=g.fh("iv-drawer-close-button",a.C);a.isInitialized=!0},v1a=function(a){var b=g.fh("iv-drawer-close-button",a.C);
a.context.j.Na(b,"click",a.vX,a);a.context.j.Na(a.u,"touchend",function(){a.va.start()});
a.context.j.Na(a.u,"scroll",a.PX,a);a.context.u.subscribe("onHideControls",function(){a.La=!0});
a.context.u.subscribe("onShowControls",function(){a.La=!1});
a.context.u.subscribe("onVideoAreaChange",function(){a.La=g.co(a.G.getRootNode(),"ytp-autohide")});
a.W.push(g.Nx("iv-button-shown",a.IZ,a));a.W.push(g.Nx("iv-button-hidden",a.HZ,a));a.W.push(g.Nx("iv-teaser-shown",a.cU,a));a.W.push(g.Nx("iv-teaser-hidden",a.KZ,a));a.W.push(g.Nx("iv-teaser-clicked",a.bU,a))},x1a=function(a,b){var c;
return b.onClickCommand&&"engagement-panel-error-corrections"===(null==(c=g.Vu(b.onClickCommand,g.CYa))?void 0:c.targetId)?(a.Y=b,!0):!1},y1a=function(a,b){var c,d=null==(c=a.G.getVideoData())?void 0:c.multiMarkersPlayerBarRenderer;
if(null==d?0:d.markersMap){var e;for(c=0;(null==(e=d)?void 0:e.markersMap.length)>c;c++){var f=void 0,h=null==(f=d)?void 0:f.markersMap[c];if("ERROR_CORRECTION_MARKERS"===h.key&&(f=void 0,(h=null==(f=h.value)?void 0:f.markers)&&0<h.length))return d=void 0,b.startMs=(null==(d=g.Vu(h[0],g.$Za))?void 0:d.timeRangeStartMillis)||0,a.Y=null,!0}}a.Y=b;return!1},f5=function(a,b){if(!x1a(a,b)||y1a(a,b)){var c=z1a(a,b);
if(c){var d={card:b,wG:c.element,bQ:!1};if(!b.onClickCommand){a.isInitialized||w1a(a);t1a(a,b.id);var e=A1a(a,d);g.hc(a.cards,e,0,d);c.xa(a.u,e);a.yB()}b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.B||(a.j=d,j5(a),B1a(a,d),d5(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.G.getCurrentTime(),5E3>c&&c>b.startMs&&C1a(a,d),a.addCueRange(b.startMs,b.startMs+1,b.id,function(){C1a(a,d)}),j5(a))}}},z1a=function(a,b){switch(b.type){case "simple":var c=a.ra;
var d=b.displayDomain?{F:"div",L:"iv-card-image-text",Z:b.displayDomain}:void 0;var e=k1a(b);d={F:"div",Da:["iv-card"],S:[{F:"a",L:"iv-click-target",T:{href:b.url?W4(b.url)||"":""},S:[Z4(b.imageUrl,d),{F:"div",L:"iv-card-content",S:[Y4("h2",void 0,b.title),e]}]}]};d=new g.W(d);$4(c,g.eh("iv-click-target",d.element),b,b.url);b=d;break;case "collaborator":c=a.ra;d={F:"div",Da:["iv-card","iv-card-channel"],S:[{F:"a",Da:["iv-click-target"],T:{href:W4(b.url)||"","data-ytid":b.channelId},S:[Z4(b.profileImageUrl),
{F:"div",L:"iv-card-content",S:[i1a(b),{F:"h2",L:"iv-card-primary-link",Z:b.title},j1a(b)]}]}]};d=new g.W(d);$4(c,g.eh("iv-click-target",d.element),b,b.url);b=d;break;case "playlist":c=a.ra;d={F:"div",Da:["iv-card","iv-card-playlist"],S:[{F:"a",L:"iv-click-target",T:{href:W4(b.url)||""},S:[Z4(b.xA,{F:"div",L:"iv-card-image-overlay",S:[{F:"span",L:"iv-card-playlist-video-count",Z:b.playlistVideoCount}]}),{F:"div",L:"iv-card-content",S:[i1a(b),Y4("h2","iv-card-primary-link",b.title),j1a(b)]}]}]};d=
new g.W(d);$4(c,g.eh("iv-click-target",d.element),b,b.url);b=d;break;case "productListing":c=a.ra;var f=!g.Xb(b.offers);d=["iv-card"];e="";var h=k1a(b);f&&(d.push("iv-card-product-listing"),e="iv-card-primary-link",h=b.offers[0],f=[],h.price&&f.push({F:"div",L:"iv-card-offer-price",Z:h.price}),h.merchant&&f.push({F:"div",L:"iv-card-offer-merchant",Z:h.merchant}),h={F:"div",S:f});f=b.url?W4(b.url)||"":"";d={F:"div",Da:d,T:{tabindex:"0"},S:[{F:"a",Da:["iv-card-image","iv-click-target"],T:{style:"background-image: url("+
b.imageUrl+");",href:f,"aria-hidden":"true",tabindex:"-1"}},{F:"div",L:"iv-card-content",S:[b.sponsored?{F:"div",L:"iv-card-sponsored",S:["Sponsored",{F:"div",L:"iv-ad-info-container",S:[{F:"div",L:"iv-ad-info",Z:"{{adInfo}}"},{F:"div",L:"iv-ad-info-icon-container",S:[{F:"div",L:"iv-ad-info-icon"},{F:"div",L:"iv-ad-info-callout"}]}]}]}:"",{F:"a",L:"iv-click-target",T:{href:f},S:[Y4("h2",e,b.title),h]}]}]};d=new g.W(d);e=g.nh("span");g.uh(e,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
d.Qd(e,"adInfo");$4(c,g.eh("iv-click-target",d.element),b,b.url);b=d;break;case "video":c=a.ra;d=b.videoDuration?{F:"span",L:"iv-card-video-duration",Z:b.videoDuration}:void 0;e=b.isLiveNow?{F:"span",Da:["yt-badge","yt-badge-live"],Z:"LIVE NOW"}:null;f={F:"div",Da:["iv-card","iv-card-video"],S:[{F:"a",L:"iv-click-target",T:{href:(null==(h=b.url)?void 0:W4(h))||""},S:[Z4(b.xA,d),{F:"div",L:"iv-card-content",S:[i1a(b),Y4("h2","iv-card-primary-link",b.title),j1a(b),e]}]}]};d=new g.W(f);$4(c,g.eh("iv-click-target",
d.element),b,b.url);b=d;break;default:return null}a.G.R().experiments.gb("web_rounded_containers")&&g.eo(b.element,"ytp-rounded-info");return b},A1a=function(a,b){if(0===a.cards.length)return 0;
a=g.Vb(a.cards,function(c){return b.card.startMs>c.card.startMs||b.card.startMs===c.card.startMs&&b.card.timestamp>=c.card.timestamp?!0:!1});
return-1===a?0:a+1},D1a=function(a){return a.j?"productListing"===a.j.card.type:g.Nd(a.cards,function(b){return"productListing"===b.card.type})},j5=function(a){g.N(a.G.getRootNode(),"ytp-cards-shopping-active",D1a(a))},C1a=function(a,b){if(!g.co(a.G.getRootNode(),"ytp-cards-teaser-shown")){if(a.j!==b){var c=g.uz(),d=a.j?a.j.card.mf:a.mf;
c&&d&&g.Dz(c,[d]);a.j=b;j5(a)}(c=a.isInitialized&&"none"==a.element.style.display)||(c=a.context.G.getPlayerState(),d=0===c&&0===a.context.G.getCurrentTime(),c=!(1===c||3===c||d));c||b.card.teaserDurationMs&&a.G.qw(!0,{teaserText:b.card.teaserText,durationMs:b.card.teaserDurationMs,onClickCommand:b.card.onClickCommand});a.ib.isActive()||((!a.B||!a.va.isActive()&&a.La)&&B1a(a,b),a.ib.start(910+b.card.teaserDurationMs))}},B1a=function(a,b){a.V.ub?(b=new K4([0,
a.u.scrollTop],[0,b.wG.offsetTop],600,D0a),a.context.B.Na(b,"animate",function(c){a.u.scrollTop=c.y}),a.context.B.Na(b,"finish",function(c){a.u.scrollTop=c.y}),b.play()):(g.PK(a.V,!0),a.u.scrollTop=b.wG.offsetTop,g.PK(a.V,!1))},k5=function(a){return a.j&&a.j.card?a.j.card:a.cards[0]&&a.cards[0].card?a.cards[0].card:null},s1a=function(a,b){return g.Ub(a.cards,function(c){return c.card.id===b})},l5=function(a,b,c){a5.call(this,a,b);
this.annotation=c;this.isActive=!1},E1a=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},m5=function(a,b,c){l5.call(this,a,b,c);
this.u=null;this.J=!1;this.B=null;this.C=!1;this.j=this.I=this.D=null},F1a=function(a,b){var c=void 0===c?0:c;
var d=B0a(b).width;g.El(b,d);c=new J0a(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,C0a);g.M(a,c);a.context.B.Na(c,"begin",function(){g.Kl(b,!0)});
c.play()},I1a=function(a,b){if(b.channel_name){var c=a.createElement({F:"div",
Da:["iv-branding-context-name"],Z:b.channel_name}),d=a.createElement({F:"div",Da:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.j=new g.LO(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,e.signInUrl,a.context.G),a.j.xa(d));var f=a.createElement({F:"div",Da:["iv-branding-context-subscribe-caret"]}),h=a.createElement({F:"div",Da:["branding-context-container-inner"]});
h.appendChild(f);h.appendChild(c);h.appendChild(d);g.Kl(h,!1);a.context.U.K("web_rounded_containers")&&g.eo(h,"ytp-rounded-branding-context");var l=a.createElement({F:"div",Da:["branding-context-container-outer"]});l.appendChild(h);g.yl(l,"right",b.image_width+"px");a.element.appendChild(l);a.B=new g.Wn(function(){G1a(a,h,l)},500);
g.M(a,a.B);a.context.j.Na(a.element,"mouseover",function(){H1a(a,h,l,f,b.image_height)});
a.context.j.Na(a.element,"mouseout",function(){a.B.start()})}},H1a=function(a,b,c,d,e){a.B.stop();
if(!a.C){var f=g.Jl(b);a.j||(b.style.width=g.Dl(f.width,!0),c.style.width=g.Dl(f.width,!0));g.yl(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.yl(d,"right","1px");a.C=!0;g.Kl(b,!0);a.D=new g.Wn(function(){g.eo(this.element,"iv-branding-active")},0,a);
a.D.start()}},G1a=function(a,b,c){g.go(a.element,"iv-branding-active");
a.I=new g.Wn(function(){g.Kl(b,!1);a.j||(c.style.width=g.Dl(0,!0))},250);
a.I.start();a.C=!1},J1a=function(a,b,c,d,e,f,h){this.j=a;
this.B=b;this.U=c;this.videoData=d;this.logger=e;this.G=f;this.u=h},K1a=function(a,b,c){l5.call(this,a,b,c);
var d=this;this.N=this.isCollapsed=this.V=!1;this.I=5E3;this.u=this.B=this.j=this.C=null;this.J=this.createElement({F:"div",Da:["iv-promo-contents"]});this.D=new g.Wn(function(){d.j.setAttribute("aria-hidden","true");g.Kl(d.B,!1);g.Kl(d.u,!0)},700,this);
g.M(this,this.D)},M1a=function(a){var b=a.annotation.data;
if("cta"===a.annotation.style)var c=6;else if("video"===a.annotation.style||"playlist"===a.annotation.style)c=7;a.I=b.collapsedelay_ms||a.I;var d=["iv-promo","iv-promo-inactive"];a.element.setAttribute("aria-hidden","true");a.element.setAttribute("aria-label","Promotion");a.element.tabIndex=0;var e=a.annotation.me(),f=b.image_url;if(f){var h=a.createElement({F:"div",Da:["iv-promo-img","iv-click-target"]});f=a.createElement({F:"img",T:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&
!b.is_live?(f=a.createElement({F:"span",L:"iv-promo-video-duration",Z:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=a.createElement({F:"span",L:"iv-promo-playlist-length",Z:b.playlist_length.toString()}),h.appendChild(f));e&&b5(a,h,e,a.annotation.id,b.session_data,void 0,c)}e?(f=a.createElement({F:"a",L:"iv-promo-txt"}),g.Cg(f,W4(e)),a.j=f):a.j=a.createElement({F:"div",L:"iv-promo-txt"});switch(a.annotation.style){case "cta":case "website":var l=a.createElement({F:"p",S:[{F:"strong",
Z:b.text_line_1}]});var m=a.createElement({F:"p",S:[{F:"span",L:"iv-promo-link",Z:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=a.createElement({F:"button",Da:["iv-promo-round-expand-icon","ytp-button"]});f=a.createElement({F:"button",Da:["iv-button","iv-promo-button"],S:[{F:"span",L:"iv-button-content",Z:f}]});var p=a.createElement({F:"div",L:"iv-promo-button-container"});p.appendChild(f);e&&b5(a,a.element,e,a.annotation.id,b.session_data,void 0,c)}g.eo(a.j,
"iv-click-target");e&&b5(a,a.j,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=a.createElement({F:"p",S:[{F:"span",Z:b.text_line_1}]}),m=a.createElement({F:"p",S:[{F:"strong",Z:b.text_line_2}]}),b.is_live&&(l=m,m=a.createElement({F:"span",Da:["yt-badge","iv-promo-badge-live"],Z:"LIVE NOW"})),g.eo(a.j,"iv-click-target"),e&&b5(a,a.j,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.j.appendChild(l);m&&a.j.appendChild(m);a.J.appendChild(a.j);p&&
a.J.appendChild(p);c=a.createElement({F:"div",L:"iv-promo-actions"});a.u=a.createElement({F:"button",Da:["iv-promo-expand","ytp-button"]});a.u.title="Expand";a.context.j.Na(a.u,"click",function(q){L1a(a,5E3,q)});
c.appendChild(a.u);g.Kl(a.u,!1);a.context.j.Na(a.element,"mouseover",a.JY,a);a.context.j.Na(a.element,"mouseout",a.IY,a);a.context.j.Na(a.element,"touchend",function(q){L1a(a,5E3,q)});
a.B=a.createElement({F:"button",Da:["iv-promo-close","ytp-button"]});a.B.title="Close";a.context.j.Na(a.B,"click","cta"===a.annotation.style&&b.text_line_3?a.EY:a.DY,a);c.appendChild(a.B);g.fo(a.element,d);h&&(a.element.appendChild(h),n&&h.appendChild(n));a.element.appendChild(a.J);a.element.appendChild(c)},L1a=function(a,b,c){c.stopPropagation();
N1a(a);O1a(a,b);a.j.focus()},P1a=function(a){a.isCollapsed||a.N||a.C||(g.eo(a.element,"iv-promo-collapsed"),a.isCollapsed=!0,a.D.start())},N1a=function(a){a.D.stop();
a.isCollapsed&&(g.ho(a.element,["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.j&&a.j.removeAttribute("aria-hidden"),g.Kl(a.u,!1),g.Kl(a.B,!0))},O1a=function(a,b){a.C||(a.C=g.Qh(function(){Q1a(this);
P1a(this)},b,a))},Q1a=function(a){a.C&&(g.C.clearTimeout(a.C),a.C=null)},R1a=function(a){this.G=a},u1a=function(a,b,c){b&&(c?n5(a,b.map(function(d){return g.Pn(d,c)})):n5(a,b))},n5=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.r(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.Qw(m,f);d&&(e++,0!==d&&a.G.sendVideoStatsEngageEvent(d,f))},S1a=function(a){g.GN.call(this,a);
var b=this;this.loadNumber=0;this.I={};this.logger=new R1a(this.player);this.D=new g.SD(this);this.C=this.Zm=null;this.events=new g.SD(this);this.J=this.j=null;this.N=[];g.M(this,this.D);this.D.P(this.player,"onVideoAreaChange",function(){b.X("onVideoAreaChange")});
this.D.P(this.player,"onHideControls",function(){b.X("onHideControls")});
this.D.P(this.player,"onShowControls",function(){b.X("onShowControls")});
this.D.P(this.player,"resize",function(d){b.X("resize",d)});
this.D.P(this.player,"presentingplayerstatechange",function(d){b.X("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.dU,this);this.subscribe("resize",this.tD,this);this.player.R().Y.subscribe("vast_info_card_add",this.pR,this);g.M(this,this.events);this.V=this.createElement({F:"div",L:"video-custom-annotations"});this.u=new g.W({F:"div",Da:["ytp-player-content","ytp-iv-player-content"]});g.M(this,this.u);g.qN(this.player,this.u.element,4);this.u.hide();this.B=new g.W({F:"div",Da:["ytp-iv-video-content"]});g.M(this,this.B);a=this.createElement({F:"div",L:"video-annotations"});
a.appendChild(this.V);this.B.element.appendChild(a);this.Ct()&&this.load();var c=this.createElement({F:"style"});(g.ch("HEAD")[0]||document.body).appendChild(c);g.ef(this,function(){g.rh(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},T1a=function(a){a=a.createElement({F:"div",
Da:["annotation","annotation-type-custom"]});g.Kl(a,!1);return a},U1a=function(a,b){b=!b.isCued()&&!g.V(b,1024);
g.PK(a.u,b);g.PK(a.B,b)},V1a=function(a,b){for(var c={},d=g.r(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Pa(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(V1a(a,e))}return c},Z1a=function(a){var b=a.player.getVideoData();
if(b.Ta){var c=a.player.R().Y.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=b.videoId;a.loaded&&a.loadNumber===a.loadNumber&&a.player.getVideoData().videoId===e&&(h=g.qu(h)&&h.responseXML?h.responseXML:null)&&W1a(a,h)}};
g.yv()&&(d.onFinish=X1a(a,d.onFinish));d.postParams={ic_only:"1"};Y1a(d,c);g.xu(b.Ta,d)}}},Y1a=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.Vx&&(a.postParams.ic_coll=b.Vx);b.DB&&(a.postParams.ic_xml=b.DB);b.CA&&(a.postParams.ic_track=b.CA)},$1a=function(a){var b=new g.W({F:"div"});
g.Kl(b.element,!1);var c=new p1a(a.player,b.element,o5(a));g.M(c,b);b.xa(a.u.element);c.mA();return c},o5=function(a){if(!a.J){var b=new M4(a);
g.M(a,b);var c=new g.Rj(a);g.M(a,c);a.J=new J1a(b,c,a.player.R(),a.player.getVideoData(),a.logger,a.player,a.Ne)}return a.J},W1a=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.uz();if(e){var f=g.tz();f&&g.yz(void 0,e,f,[g.nz(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=V1a(a,b[d]);e=null;try{if(f){var h=f.id,l=/.+/;var m="string"===typeof h&&null!=l&&null!=h&&h.match(l)?h:"";var n=V4(f.type,a2a),p=V4(f.style,b2a),q=Z0a(f.data),v=0!==q.length?JSON.parse(q):{};var w=f.action;f=e1a;if(null==w)var y=null;else if(g.Oa(w)){l=[];for(var A=g.r(w),B=A.next();!B.done;B=A.next()){var E=f(B.value);
E&&l.push(E)}y=l}else{var H=f(w);y=H?[H]:[]}e=m&&n?new f1a(m,n,p,y,v):null}else e=null}catch(S){}if(e)if("branding"===e.type||"promotion"===e.type){f=a;l=e;var G=T1a(f),I=null;switch(l.type){case "branding":if(f.player.R().Rc)break;f.u.element.appendChild(G);I=new m5(G,o5(f),l);break;case "promotion":g.qN(f.player,G,4),I=new K1a(G,o5(f),l)}I&&I.mA();if(f=I)g.M(a,f),a.I[e.id]=f}else if("card"===e.type||"drawer"===e.type){a.j||(a.j=$1a(a),g.M(a,a.j));if("card"===e.type){c=a.j;var P=e&&e.data&&e.data.card_type;
f=e.data;if(P)switch(l=f.tracking||{},l={impression:l.impression,click:l.click,close:l.close,GS:l.teaser_impression,vE:l.teaser_click},G=f.tracking_params||{},I=null,P){case "collaborator":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,fm:G.card?g.nz(G.card):null,Cj:G.teaser?g.nz(G.teaser):null,mf:G.icon?g.nz(G.icon):null,
channelId:f.channel_id,customMessage:f.custom_message?f.custom_message:null,profileImageUrl:f.image_url,title:f.title,metaInfo:f.meta_info,url:X4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};f5(c,e);break;case "playlist":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,
fm:G.card?g.nz(G.card):null,Cj:G.teaser?g.nz(G.teaser):null,mf:G.icon?g.nz(G.icon):null,xA:f.image_url,playlistVideoCount:f.playlist_video_count,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,url:X4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};f5(c,e);break;case "productListing":f.signin_url&&(I=X4({target:"current",value:f.signin_url}));P=[];for(var K=f.offers||[],Q=0;Q<K.length;Q++)P.push(new l1a(g.Xg(K[Q].merchant),
g.Xg(K[Q].price)));e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,fm:G.card?g.nz(G.card):null,Cj:G.teaser?g.nz(G.teaser):null,mf:G.icon?g.nz(G.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,Ux:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?
f.custom_message:null,url:X4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),q2a:I,p2a:f.signin_title?f.signin_title:void 0,o2a:f.signin_message?f.signin_message:void 0,offers:P,onClickCommand:null};f5(c,e);break;case "simple":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,fm:G.card?g.nz(G.card):
null,Cj:G.teaser?g.nz(G.teaser):null,mf:G.icon?g.nz(G.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,Ux:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?f.custom_message:null,url:X4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};f5(c,e);break;case "video":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,
startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,fm:G.card?g.nz(G.card):null,Cj:G.teaser?g.nz(G.teaser):null,mf:G.icon?g.nz(G.icon):null,xA:f.image_url,videoDuration:f.video_duration||null,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,isLiveNow:!!f.is_live_now,url:X4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null},f5(c,e)}}else q1a(a.j,e);c=
!0}}c&&(F4(a.player),a.tD())},c2a=function(a,b){var c=!1;
a.j||(a.j=$1a(a),g.M(a,a.j));for(var d=g.r(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(r1a(a.j,e.cardRenderer),c=!0);c&&(c=a.j,d=b.headerText?g.sA(b.headerText):"",g.uh(c.Fb,d),c.N&&c.N.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.Fa=b.trackingParams?g.nz(b.trackingParams):null,c.J=b.closeButton.infoCardIconRenderer.trackingParams?g.nz(b.closeButton.infoCardIconRenderer.trackingParams):null,c.mf=b.icon.infoCardIconRenderer.trackingParams?
g.nz(b.icon.infoCardIconRenderer.trackingParams):null,F4(a.player),a.tD())},d2a=function(a,b,c,d,e){if(!a.player.R().Rc){var f=[];
b.navigationEndpoint&&b.navigationEndpoint.browseEndpoint&&b.navigationEndpoint.browseEndpoint.browseId&&f.push(new b1a("openUrl","click",new $0a("/channel/"+b.navigationEndpoint.browseEndpoint.browseId,"new",!0,!0)));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&
b.subscribeButton.subscribeButtonRenderer){d.channel_id=b.subscribeButton.subscribeButtonRenderer.channelId;var l;b=b.subscribeButton.subscribeButtonRenderer;h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.sA(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.sA(b.subscriberCountText))):(b.subscriberCountText&&(e=g.sA(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.sA(b.subscriberCountWithSubscribeText)));var m,n,p=(null==(l=b.signInEndpoint)?void 0:
null==(m=l.commandMetadata)?void 0:null==(n=m.webCommandMetadata)?void 0:n.url)||"";l={subscribeText:g.sA(b.unsubscribedButtonText),subscribeCount:e||"",unsubscribeText:g.sA(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:p};d.standalone_subscribe_button_data=l}f=new f1a(c,"branding","branding",f,d);l=T1a(a);a.u.element.appendChild(l);f=new m5(l,o5(a),f);f.mA();g.M(f,f);a.I[c]=f}},X1a=function(a,b){return function(){var c=
g.za.apply(0,arguments);
a.isDisposed()||a.N.push(g.Sn.Hh(function(){b.apply(null,g.t(c))}))}},e2a=function(a){return"annotation-editor"===a||"live-dashboard"===a};
g.jN.prototype.qw=g.ba(17,function(a,b){var c=g.XN(this.kb());c&&c.qw(a,b)});
var H4={},I4=null;g.Xa(K4,g.po);g.k=K4.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.j)this.progress=0,this.coords=this.u;else if(this.Nc())return!1;J4(this);this.startTime=a=g.Ua();-1==this.j&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.D=this.startTime;this.progress||this.pD();this.Rj("play");-1==this.j&&this.Rj("resume");this.j=1;var b=g.Ra(this);b in H4||(H4[b]=this);F0a();G0a(this,a);return!0};
g.k.stop=function(a){J4(this);this.j=0;a&&(this.progress=1);H0a(this,this.progress);this.Rj("stop");this.Iz()};
g.k.pause=function(){this.Nc()&&(J4(this),this.j=-1,this.Rj("pause"))};
g.k.ea=function(){0==this.j||this.stop(!1);this.Rj("destroy");K4.Le.ea.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.hF=function(){this.Rj("animate")};
g.k.Rj=function(a){this.dispatchEvent(new I0a(a,this))};
g.Xa(I0a,g.ff);g.Xa(L4,K4);L4.prototype.C=function(){};
L4.prototype.hF=function(){this.C();L4.Le.hF.call(this)};
L4.prototype.Iz=function(){this.C();L4.Le.Iz.call(this)};
L4.prototype.pD=function(){this.C();L4.Le.pD.call(this)};
g.Xa(J0a,L4);J0a.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};var i5=new g.Vo("browseEndpoint");g.u(M4,g.L);M4.prototype.Na=function(a,b,c,d){c=(0,g.Sa)(c,d||this.u);a=g.ux(a,b,c);this.j.push(a);return a};
M4.prototype.ZC=function(a,b,c,d){c=(0,g.Sa)(c,d||this.u);a=g.Doa(a,b,c);this.j.push(a);return a};
M4.prototype.yc=function(a){g.vx(a);g.Zb(this.j,a)};
M4.prototype.ea=function(){g.vx(this.j);this.j.length=0;g.L.prototype.ea.call(this)};g.u(M0a,g.GN);g.k=M0a.prototype;g.k.load=function(){g.GN.prototype.load.call(this);if(!P4(this)){var a=g.OBa(this.player.getVideoData());a?(a=L0a(a,N0a(this)),Q4(this,a,!1)):O0a(this)}};
g.k.unload=function(){Q4(this,null);this.B&&(this.B.abort(),this.B=null);g.GN.prototype.unload.call(this)};
g.k.wg=function(a,b){return P4(this)?"loadCustomEndscreenRenderer"===a?(a=L0a(b,"new"),Q4(this,a),!0):null:null};
g.k.getOptions=function(){return P4(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.yb=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<f2a.length;f++){var h=Math.abs(b.width-f2a[f]);if(-1===e||d>=h)e=f,d=h}d=g2a[e];this.u&&g.yl(this.u.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.j[f],
h=this.D[f],e&&h){var l=h.width*c/h.aspectRatio,m=Math.round(h.width*a.width);f=Math.round(l*a.height);var n=a.left+Math.round(h.left*a.width),p=a.top+Math.round(h.top*a.height);g.Il(e.element,m,f);g.El(e.element,n,p);this.W&&(g.ho(e.element,h2a),256<m||256<f?g.eo(e.element,"ytp-ce-large-round"):96<m||96<f?g.eo(e.element,"ytp-ce-medium-round"):g.eo(e.element,"ytp-ce-small-round"));g.ho(e.element,i2a);m=h.left+h.width/2;h=h.top+l/2;g.eo(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":
.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.ho(e.element,g2a);g.eo(e.element,d);(e=g.dh(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.yl(e,"height",f+"px")}}}}};
g.k.onCueRangeEnter=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())U4(this,this.endscreen.impressionUrls),(a=g.uz())&&this.endscreen.visualElement&&g.zz(a,this.endscreen.visualElement);else{a=a.getId().substring(15);var b=this.j[a],c=this.D[a];g.eo(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.eo(b,"ytp-ce-shown");U4(this,c.impressionUrls);(b=g.uz())&&g.zz(b,c.visualElement);this.player.R().B&&this.player.Ma("endscreenelementshown",
a)}};
g.k.onCueRangeExit=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.j[a];g.go(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.go(b,"ytp-ce-shown");this.player.R().B&&this.player.Ma("endscreenelementhidden",a)}};
g.k.O2=function(a){var b=this;a.target===window&&(new g.Wn(function(){for(var c=g.r(Object.values(b.j)),d=c.next();!d.done;d=c.next())g.ho(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var f2a=[346,426,470,506,570,640,853,1280,1920],g2a="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),i2a=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],h2a=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var a1a={xja:"current",bEa:"new"};var c1a={CLOSE:"close",zHa:"openUrl",SUBSCRIBE:"subscribe"},d1a={Iea:"click",CLOSE:"close",Dqa:"hidden",GMa:"rollOut",HMa:"rollOver",BOa:"shown"};f1a.prototype.me=function(){var a=g1a(this,function(b){return"openUrl"===b.type&&null!=b.url});
return a?a.url:null};
var b2a={waa:"anchored",DT:"branding",CHANNEL:"channel",nja:"cta",Gqa:"highlightText",yua:"label",PLAYLIST:"playlist",nKa:"popup",eRa:"speech",SUBSCRIBE:"subscribe",hUa:"title",VIDEO:"video",w_a:"website"},a2a={DT:"branding",Nca:"card",Bla:"drawer",Fqa:"highlight",aAa:"marker",nLa:"promotion",TEXT:"text",g0a:"widget"};g.u(a5,g.L);g.k=a5.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.lA(a,b,{id:c,namespace:"annotations_module"});d&&this.Va.set(a,d);e&&this.Ya.set(a,e);this.context.G.ke([a])};
g.k.mA=function(){this.context.u.subscribe("resize",this.yB,this)};
g.k.iF=function(a,b,c,d,e,f){if(this.zb)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.rh(this.element)};
g.k.yB=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=W4(a);if(f){var h=n1a(f,a.target),l=function(){a.j&&e.context.G.pauseVideo();var m=e.context.videoData.C||!1,n=g.iu(f||"");m&&n&&(n.v||n.list)?e.context.G.El(n.v,b,n.list,!1):g.$L(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);n5(this.context.logger,c,l,d);m1a(f)||(c=g.uz(),d=b.itct,c&&d&&g.Ez(c,g.nz(d)))}};
g.k.ea=function(){this.Va.clear();this.Ya.clear();g.L.prototype.ea.call(this)};
g.k.createElement=function(a){a=new g.W(a);g.M(this,a);return a.element};g.u(p1a,a5);g.k=p1a.prototype;g.k.Rp=function(){this.Y&&f5(this,this.Y)};
g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.G.getRootNode())?(a=g.Jl(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.yB=function(){var a=this.isAvailable();g.Kl(this.element,a);g.N(this.context.G.getRootNode(),g.aT.IV_DRAWER_ENABLED,a);F4(this.G)};
g.k.destroy=function(){this.G.qw(!1);try{this.G.getRootNode().removeChild(this.C)}catch(a){}g.Ox(this.W);g.vx(this.qa);this.Ta&&this.Ta.dispose();this.D&&this.D.dispose();a5.prototype.destroy.call(this)};
g.k.vX=function(){if(this.B){n5(this.context.logger,k5(this).tracking.close);var a=g.uz();a&&this.J&&g.Ez(a,this.J);e5(this)}};
g.k.PX=function(){g.N(this.C,"iv-drawer-scrolled",0<this.u.scrollTop)};
g.k.IZ=function(){var a=g.uz(),b=k5(this);b=b?b.mf:this.mf;a&&b&&g.Cz(a,[b])};
g.k.HZ=function(){var a=g.uz(),b=k5(this);b=b?b.mf:this.mf;a&&b&&g.Dz(a,[b])};
g.k.cU=function(){var a=k5(this);n5(this.context.logger,a.tracking.GS);var b=g.uz();b&&a&&g.Cz(b,[a.Cj,a.mf])};
g.k.KZ=function(){var a=g.uz(),b=k5(this);a&&b&&g.Dz(a,[b.Cj])};
g.k.bU=function(a){var b=k5(this),c=g.uz();this.j?a?(a=this.context.logger,n5(a,b.tracking.vE),a.G.sendVideoStatsEngageEvent(4,void 0),c&&b.Cj&&g.Ez(c,b.Cj)):(a=this.context.logger,n5(a,b.tracking.vE),a.G.sendVideoStatsEngageEvent(4,void 0),c&&b.mf&&g.Ez(c,b.mf)):(a=this.context.logger,n5(a,b.tracking.vE),a.G.sendVideoStatsEngageEvent(4,void 0),c&&this.mf&&g.Ez(c,this.mf))};g.u(l5,a5);l5.prototype.mA=function(){a5.prototype.mA.call(this);E1a(this)};
l5.prototype.show=function(){a5.prototype.show.call(this);var a=g.uz(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.Cz(a,[g.nz(b.itct)])};
l5.prototype.hide=function(){a5.prototype.hide.call(this);var a=g.uz(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.Dz(a,[g.nz(b.itct)])};g.u(m5,l5);
m5.prototype.show=function(){if(!this.isActive){l5.prototype.show.call(this);if(!this.J){g.eo(this.element,"iv-branding");var a=this.annotation.data;this.u=this.createElement({F:"img",Da:["branding-img","iv-click-target"],T:{"aria-label":"Channel watermark",src:a.image_url,width:a.image_width,height:a.image_height}});g.Kl(this.u,!1);var b=this.context.U.K("html5_player_branding_button_killswitch")?this.createElement({F:"div",Da:["branding-img-container"]}):this.createElement({F:"button",Da:["branding-img-container",
"ytp-button"]});b.appendChild(this.u);this.element.appendChild(b);var c=this.annotation.me();c&&(b=this.context.U.K("html5_player_branding_button_killswitch")?this.u:b,b5(this,b,c,this.annotation.id,a.session_data));I1a(this,a);this.J=!0}g.Kl(this.element,!0);this.isActive=!0;this.u&&F1a(this,this.u)}};
m5.prototype.hide=function(){this.isActive&&(l5.prototype.hide.call(this),g.Kl(this.element,!1),this.isActive=!1)};
m5.prototype.destroy=function(){this.j&&(this.j.dispose(),this.j=null);l5.prototype.destroy.call(this)};g.u(K1a,l5);g.k=K1a.prototype;g.k.show=function(){this.isActive||(l5.prototype.show.call(this),this.V||(M1a(this),this.V=!0),g.Kl(this.element,!0),g.Qh(function(){g.go(this.element,"iv-promo-inactive")},100,this),this.element.removeAttribute("aria-hidden"),this.isActive=!0,Q1a(this),N1a(this),O1a(this,this.I))};
g.k.hide=function(){this.isActive&&(g.eo(this.element,"iv-promo-inactive"),this.isActive=!1,this.element.setAttribute("aria-hidden","true"))};
g.k.iF=function(a,b,c,d,e,f){return this.isCollapsed?!1:l5.prototype.iF.call(this,a,b,c,d,e,f)};
g.k.JY=function(a){this.N=!0;L1a(this,500,a)};
g.k.IY=function(){this.N=!1;P1a(this)};
g.k.DY=function(a){a.stopPropagation();this.hide()};
g.k.EY=function(a){a.stopPropagation();Q1a(this);this.isCollapsed=!0;g.eo(this.element,"iv-promo-collapsed-no-delay");this.D.start()};
g.k.destroy=function(){this.D.dispose();l5.prototype.destroy.call(this)};g.u(S1a,g.GN);g.k=S1a.prototype;g.k.wg=function(a,b){if(!e2a(this.player.R().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.fXa(b))&&W1a(this,a),!0;case "removeCustomAnnotationById":return b&&this.j&&(t1a(this.j,b),F4(this.player)),!0}return null};
g.k.getOptions=function(){return e2a(this.player.R().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.Ct=function(){var a=this.player.R(),b=this.player.getVideoData();return b.C&&a.pfpChazalUi?!1:1===(a.annotationsLoadPolicy||b.annotationsLoadPolicy)&&!b.xQ||a.Y.get(b.videoId)||g.gI(b)||g.hI(b)?!0:!1};
g.k.tD=function(){if(this.B){var a=this.player.bb().getVideoContentRect(!0);g.Il(this.B.element,a.width,a.height);g.El(this.B.element,a.left,a.top)}if(this.j){var b=this.player.Tj();a=this.j;b=b.width;g.N(a.C,"iv-drawer-small",426>=b);g.N(a.C,"iv-drawer-big",1280<=b)}};
g.k.dU=function(a){U1a(this,a.state);g.V(a.state,2)&&(this.xi()&&this.cm()&&2!==this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.qw(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.C=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.qu(h)&&h.responseXML?h.responseXML:null)&&(W1a(b,h),g.eo(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.GN.prototype.load.call(this);U1a(this,this.player.Bb());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.yv()&&(a=X1a(this,a));var e={format:"XML",onFinish:a,onError:function(){b.C=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.R().Y.get(d);f&&Y1a(e,f);f=f&&(f.DB||f.Vx);if(!c.Cn||f)c.Ta?this.C=g.xu(c.Ta,e):(this.Zm=function(){b.onVideoDataChange(e)},this.player.addEventListener("videodatachange",this.Zm));
g.qN(this.player,this.B.element,4);this.tD();(f=g.gI(c))&&c2a(this,f);(f=g.hI(c))&&f.featuredChannel&&d2a(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null)};
g.k.onVideoDataChange=function(a){var b=this.player.getVideoData();b.Ta&&(this.Zm&&(this.player.removeEventListener("videodatachange",this.Zm),this.Zm=null),this.C=g.xu(b.Ta,a))};
g.k.unload=function(){this.player.zf("annotations_module");for(var a=g.r(Object.keys(this.I)),b=a.next();!b.done;b=a.next())this.I[b.value].destroy();this.J=null;this.j&&(this.j.destroy(),this.j=null,F4(this.player));this.C&&(this.C.abort(),this.C=null);this.I={};this.u.hide();g.GN.prototype.unload.call(this);this.B.detach();this.Zm&&(this.player.removeEventListener("videodatachange",this.Zm),this.Zm=null)};
g.k.pR=function(a){a===this.player.getVideoData().videoId&&(this.loaded?Z1a(this):this.load())};
g.k.xi=function(){return!!this.j&&this.j.isAvailable()};
g.k.cm=function(){return!!this.j&&this.j.B};
g.k.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.xi();this.j&&(a?c?d5(this.j,c,b):d5(this.j,"YOUTUBE_DRAWER_AUTO_OPEN",b):e5(this.j))};
g.k.qw=function(a,b){this.player.X(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.ea=function(){this.player.R().Y.unsubscribe("vast_info_card_add",this.pR,this);g.go(this.player.getRootNode(),g.aT.IV_DRAWER_OPEN);for(var a=this.N,b=g.Sn,c=0,d=a.length;c<d;c++)b.Pk(a[c]);this.N.length=0;g.GN.prototype.ea.call(this)};
g.k.createElement=function(a){a=new g.W(a);g.M(this,a);return a.element};g.FN("annotations_module",S1a);g.FN("creatorendscreen",M0a);})(_yt_player);
